### ISSUE TITLE
last elements of a sequence are never detected

### ISSUE THREAD

**Issue by Jero-M** [rsgalloway/pyseq#40] opened 2017-09-11 20:59 UTC
Using the last element of a sequence to create a new sequence is not recognized. Example:

image.0001.png
image.0002.png
image.0003.png
image.0004.png

Creating a sequence object using frame 1, 2 or 3 works perfectly and it returns a sequence with a length of 4. However, checking for membership using contains() with image.0004.png returns False.

**Comment by rsgalloway** [comment] 2017-09-15 01:00
Not sure I can reproduce this. Here's what I tried:

```
s0 = Sequence(get_sequences("tests/files/bnc01_TinkSO_tx_0_ty_0.*.tif")[0])
s1 = Sequence(s0[:])
assert len(s0) == len(s1)
assert s0 == s1
for i in s0:
    assert s1.contains(i)
```

Did you try with the latest version in the repo?

**Comment by Jero-M** [comment] 2017-09-15 17:36
Hi Ryan, here is what I get:


path = "/home/jmaggi/Documents/pyseq_test"
img_seq = get_sequences(path)[0]
if img_seq.contains("pig_v001.0012.ifd"):
    print "TRUE - pig_v001.0012.ifd is in {0}".format(img_seq)
else:
    print "FALSE - pig_v001.0012.ifd is not in {0}".format(img_seq)


Here is my output:
Directory contents:
['pig_v001.0001.ifd',
 'pig_v001.0002.ifd',
 'pig_v001.0003.ifd',
 'pig_v001.0004.ifd',
 'pig_v001.0005.ifd',
 'pig_v001.0006.ifd',
 'pig_v001.0007.ifd',
 'pig_v001.0008.ifd',
 'pig_v001.0009.ifd',
 'pig_v001.0010.ifd',
 'pig_v001.0011.ifd',
 'pig_v001.0012.ifd']
-----------------
pyseq Sequence objects
<pyseq.Sequence "pig_v001.1-12.ifd">
Test for membership
FALSE - pig_v001.0012.ifd is not in pig_v001.1-12.ifd


I think the problem comes from the diff() function (line 782), here is what it prints (I added some stuff to print what every value is doing) when I use the contains() method exactly with the same arguments as I did above:

f1 = pig_v001.0012.ifd
f2 = pig_v001.0012.ifd
len(l1) = 2
len(l2) = 2
for i in range(0, 2)
i = 0
m1.start = 5
m2.start = 5
m1.group = 001
m1.group = 001
if m1.start() == m2.start() and m1.group() != m2.group():
False
i = 1
m1.start = 9
m2.start = 9
m1.group = 0012
m1.group = 0012
if m1.start() == m2.start() and m1.group() != m2.group():
False
d = []




________________________________

**Comment by broganross** [comment] 2017-09-18 19:14
That is the correct output of 'diff'.  It only returns if two strings are identical except for the same numerical section.  So if you give it the same string it should return no difference.
I also tried to recreate your issue but couldn't:


    import pyseq
    base = "pig_v001.{:04}.ifd"
    files =[]
    for i in xrange(1, 13):
        files.append(base.format(i))

    seq = pyseq.get_sequences(files)[0]
    seq.contains("pig_v001.0012.ifd") # True


What concerns me is this:

    seq.contains("pig_v001.12.ifd") # True

Should look into it.

Jero, Can you create a minimum example that shows the behavior.  Is it possible it's not finding it because you're only checking for the file name?  Not the full path?

**Comment by Jero-M** [comment] 2017-09-21 18:11
Thanks Brogan, finding it using the full path seems to work. I was confused because even though I was using the file name, it would return True for everything else except the last item in the sequence. I mistakenly though that contains() would compare the input string with every item in the sequence, but now I see it even works with different padding.

The reason why I was doing this is that I have a file dialog and I would get all the sequence objects from that directory using pyseq and then query the user selection and check with contains() to what sequence it belonged. The problem was that selecting the last element in a sequence would return False and not return any matching sequences.

`import pyseq
import os

path = "/home/jmaggi/Documents/pyseq_test"
dir_contents = os.listdir(path)
seq_from_list = pyseq.get_sequences(dir_contents)[0]
seq_from_path = pyseq.get_sequences(path)[0]
for frame, item in enumerate(dir_contents):
    print "From List:", item, seq_from_list.contains(item)
    print "From Path:", item, seq_from_path.contains(item)
    print "From Full path:", path + "/" + item, seq_from_path.contains(path + "/" + item)
    custom_padding = "pig_v001.{0}.ifd".format(str(frame + 1).zfill(2))
    print "From Path using diff padding:", custom_padding, seq_from_path.contains(custom_padding)
    print
print dir_contents`

Output:

`From List: pig_v001.0001.ifd True
From Path: pig_v001.0001.ifd True
From Full path: /home/jmaggi/Documents/pyseq_test/pig_v001.0001.ifd True
From Path using diff padding: pig_v001.01.ifd True

From List: pig_v001.0002.ifd True
From Path: pig_v001.0002.ifd True
From Full path: /home/jmaggi/Documents/pyseq_test/pig_v001.0002.ifd True
From Path using diff padding: pig_v001.02.ifd True

From List: pig_v001.0003.ifd True
**From Path: pig_v001.0003.ifd False**
From Full path: /home/jmaggi/Documents/pyseq_test/pig_v001.0003.ifd True
From Path using diff padding: pig_v001.03.ifd True

['pig_v001.0001.ifd', 'pig_v001.0002.ifd', 'pig_v001.0003.ifd']`

**Comment by broganross** [comment] 2017-09-22 16:51
The different padding is definitely a bug that needs to be fixed.  However, ignoring that, I think what I'm seeing is the correct behavior.  At least based on the current functionality.  When a file name or file path is converted into an Item, it has `os.path.abspath` run on the path.  Meaning if your current working directory isn't where the files are you get an invalid file path.

In your example 'From List' doesn't have a valid path, but 'From Path' does.  So when you're running `contains` on 'From List' using only a file name it is run through `os.path.abspath` and ends up being the same full path as what was put into that sequence.  But, when you try `contains` on the 'From Path' it can't find a match because your file name comes out of `os.path.abspath` with an invalid file path that also doesn't match.  This is also why `contains` returns True when you give it the full path.

Assuming you run this from your home directory, you can see what I mean.

No file path is given so it uses the current directory (assuming it the user home).

    path = "/home/jmaggi/Documents/pyseq_test"
    files = os.listdir(path)
    seq = pyseq.get_sequences(files)[0]
    print seq[0].path # prints "/home/jmaggi/pig_v001.0001.ifd"

Full path given comes out with the right path.

    path = "/home/jmaggi/Documents/pyseq_test"
    seq = pyses.get_sequences(path)[0]
    print seq[0].path # prints "/home/jmaggi/Documents/pyseq_test/pig_v001.0001.ifd"

So really you should work with the full paths, and make sure you give `get_sequences` a directory or a list of fully formed file paths.

**Comment by rsgalloway** [comment] 2017-11-16 01:11
closing this as it seems the behavior is expected.

**Closed by rsgalloway** 2017-11-16 01:11 UTC
Labels: wontfix
