### ISSUE TITLE
While loop issues get_sequences/iget_sequences

### ISSUE THREAD

**Issue by lasselauch** [rsgalloway/pyseq#67] opened 2022-05-02 20:34 UTC
Made an interesting discovery today:
While searching a folder with the following filenames, `pyseq` stops to respond (!) and hangs itself.

![pyseq_while_loop_error](https://user-images.githubusercontent.com/44460746/166321224-8bcb6bf4-ffd9-4813-a85c-69355fb0b6bd.png)

My guess it's due to the nature of the `while` loop within the `get_sequences` and `iget_sequences` functions...

I was able to reproduce this issue with empty files, so here's a list of the filenames for further testing:

`['gettyimages-1364769281-2048x2048.jpg', 'gettyimages-530573048-2048x2048.jpg', 'gettyimages-1127718214-2048x2048.jpg', 'gettyimages-470543560-2048x2048.jpg', 'gettyimages-155374807-2048x2048.jpg', 'gettyimages-1182189546-2048x2048.jpg', 'gettyimages-157742535-2048x2048.jpg']`

Cheers,
Lasse

**Comment by rsgalloway** [comment] 2022-05-05 02:19
Interesting, thanks for the report. I'm able to reproduce this issue using lss as well. 

Don't think it's a problem with the while loops. Technically, the names of these files make them a sequence as far as pyseq is concerned. Looks like it finds two of them:

```
>>> seqs = get_sequences(['gettyimages-1364769281-2048x2048.jpg', 'gettyimages-530573048-2048x2048.jpg', 'gettyimages-1127718214-2048x2048.jpg', 'gettyimages-470543560-2048x2048.jpg', 'gettyimages-155374807-2048x2048.jpg', 'gettyimages-1182189546-2048x2048.jpg', 'gettyimages-157742535-2048x2048.jpg'])
>>> len(seqs)
2
```

The problem seems to be the sequences sizes:

```
>>> seqs[0].frames()
[1127718214, 1182189546, 1364769281]
```

and when formatting these sequences it's trying to calculate the missing frames on line 363 which is many (commenting out that line seems to make it work again).

```
>>> seqs[0].format()
'   3 gettyimages-%d-2048x2048.jpg [1127718214, 1182189546, 1364769281]'
```

So it seems like the solution here might be to find a smarter way to calculate missing frames in _get_missing.

**Comment by rsgalloway** [comment] 2022-05-06 03:45
@lasselauch FYI I've got a branch with a potential fix if you want to give it a try: 

https://github.com/rsgalloway/pyseq/tree/issue-67

**Comment by lasselauch** [comment] 2022-05-06 07:06
@rsgalloway Thanks, for the quick fix, that works great indeed!!! 🚀

**Comment by rsgalloway** [comment] 2022-05-06 15:23
Great, thanks for testing. I'll get this merged and deployed to pypi shortly.

**Closed** 2022-05-10 14:49 UTC
Labels: bug, performance
