### ISSUE TITLE
use scandir instead of os.walk()?

### ISSUE THREAD

**Issue by herronelou** [rsgalloway/pyseq#48] opened 2018-08-29 18:43 UTC
Hi.
Just wondering if using scandir instead of os.walk would increase performance when doing a pyseq.walk()?

**Comment by nebukadhezer** [comment] 2018-09-07 09:35
I guess it should make a huge difference.
`
try:
    from scandir import walk as walkFunction
except ImportError:
    from os import walk as walkFunction`

I used it like this in other modules..
@rsgalloway I could make a seperate PR for this ?

**Comment by rsgalloway** [comment] 2018-09-07 16:53
Sure, definitely worth testing. As I said in your other PR, we should add some regression tests to evaluate these things more consistently. I'll need to look into what CI testing is supported on github because it'd be interesting to see if performance could be tracked over time.

**Comment by herronelou** [comment] 2018-12-27 22:49
Hi,
I've given a try to this, and while it does speed up performance (in python 2.7), it changes the return types to unicode, which as we've seen in issue #45 is not always a great idea. I didn't push too far, but if you do make a patch for it make sure there's no regression there I guess.

**Comment by rsgalloway** [comment] 2024-08-14 22:13
implemented some performance improvements in 0.7.0, closing this

https://github.com/rsgalloway/pyseq/pull/71

**Closed by rsgalloway** 2024-08-14 22:13 UTC
Labels: performance
